"""
Anthropic Claude-powered hook generation service.

Replaces pattern-based templates with LLM-generated hooks using
context-aware prompt engineering and user performance history.
"""

import logging
import os
from typing import Dict, Any, List, Optional, Tuple
from dataclasses import dataclass
import httpx
import json
import asyncio

logger = logging.getLogger(__name__)

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"


@dataclass
class GeneratedHook:
    """A hook generated by Claude."""
    hook_text: str
    archetype: str
    confidence: float
    rationale: str
    estimated_retention: float
    variant_index: int


class ClaudeHookService:
    """Generate viral hooks using Anthropic Claude API."""
    
    # Hook archetypes for classification
    ARCHETYPES = [
        "question", "promise", "pattern_break", "reaction",
        "story", "statistic", "challenge", "authority"
    ]
    
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or ANTHROPIC_API_KEY
        self.client = httpx.AsyncClient(timeout=30.0)
        
        if not self.api_key:
            logger.warning("[ClaudeHook] No ANTHROPIC_API_KEY set — using fallback generation")
    
    async def generate_hooks(
        self,
        transcript_text: str,
        user_top_archetypes: List[Dict[str, Any]],
        num_variants: int = 3,
        platform: str = "tiktok",
        niche: Optional[str] = None
    ) -> List[GeneratedHook]:
        """
        Generate multiple hook variants using Claude.
        
        Args:
            transcript_text: The video transcript or caption
            user_top_archetypes: User's top-performing archetypes from analytics
            num_variants: Number of unique hooks to generate
            platform: Target platform (tiktok, instagram, youtube)
            niche: Content niche/topic (optional)
        
        Returns:
            List of GeneratedHook objects
        """
        if not self.api_key or not transcript_text:
            logger.warning("[ClaudeHook] API key missing or empty transcript — using fallback")
            return self._fallback_generation(transcript_text, num_variants)
        
        # Build the prompt
        system_prompt = self._build_system_prompt(platform, niche)
        user_prompt = self._build_user_prompt(transcript_text, user_top_archetypes, num_variants)
        
        try:
            hooks = await self._call_claude(system_prompt, user_prompt, num_variants)
            return hooks
        except Exception as e:
            logger.error(f"[ClaudeHook] API call failed: {e}")
            return self._fallback_generation(transcript_text, num_variants)
    
    def _build_system_prompt(self, platform: str, niche: Optional[str]) -> str:
        """Build the system prompt for Claude."""
        platform_guidance = {
            "tiktok": "TikTok: 1-2 seconds to capture attention. Hooks must be punchy, visual, and create immediate curiosity. Under 8 words if possible. Strong emotion or surprise.",
            "instagram": "Instagram Reels: Slightly more polished than TikTok. Hooks can be 10-12 words. Aspirational or relatable works well. Trendy language.",
            "youtube": "YouTube Shorts: Slightly longer hooks okay (15-20 words). Educational or 'how-to' angles perform well. Clear value proposition."
        }
        
        niche_guidance = f"The content niche is: {niche}. " if niche else ""
        
        return f"""You are a viral video hook specialist with expertise in short-form content optimization.

Your job is to generate attention-grabbing opening lines (hooks) for video clips.

Platform guidance: {platform_guidance.get(platform, platform_guidance['tiktok'])}

{niche_guidance}

Rules:
1. Each hook must create immediate curiosity, emotion, or surprise
2. Hooks should feel native to the platform — not corporate or sales-y
3. Use pattern interrupts, open loops, or emotional triggers
4. Never use clickbait that doesn't deliver on the content
5. Each hook should be unique — different angles on the same content
6. Rate each hook's predicted 3-second retention (0.0-1.0)
7. Classify each hook into an archetype: question, promise, pattern_break, reaction, story, statistic, challenge, authority

Return ONLY valid JSON in this exact format:
{{
  "hooks": [
    {{
      "hook_text": "The actual hook text",
      "archetype": "pattern_break",
      "confidence": 0.92,
      "rationale": "Why this hook works",
      "estimated_retention": 0.78
    }}
  ]
}}"""
    
    def _build_user_prompt(
        self,
        transcript: str,
        top_archetypes: List[Dict[str, Any]],
        num_variants: int
    ) -> str:
        """Build the user prompt with context."""
        # Truncate transcript if too long
        truncated = transcript[:2000] if len(transcript) > 2000 else transcript
        
        # Format top archetypes
        archetype_context = ""
        if top_archetypes:
            archetype_context = "User's top-performing hook archetypes (use these preferentially):\n"
            for i, arch in enumerate(top_archetypes[:3]):
                name = arch.get("pattern_type", arch.get("archetype_name", "unknown"))
                delta = arch.get("retention_delta_pct", arch.get("delta", 0))
                archetype_context += f"{i+1}. {name} (+{delta:.0f}% retention)\n"
        
        return f"""Generate {num_variants} unique, viral-worthy hooks for this video content.

{archetype_context}

Video transcript/content:
---
{truncated}
---

Generate {num_variants} hooks that:
1. Would stop someone from scrolling
2. Match the user's proven archetypes when possible
3. Each use a different angle/emotion
4. Are optimized for the platform

Return as JSON."""
    
    async def _call_claude(
        self,
        system_prompt: str,
        user_prompt: str,
        num_variants: int
    ) -> List[GeneratedHook]:
        """Call Claude API and parse response."""
        
        payload = {
            "model": "claude-sonnet-4-20250514",
            "max_tokens": 2000,
            "system": system_prompt,
            "messages": [
                {"role": "user", "content": user_prompt}
            ],
            "temperature": 0.8  # Creative but coherent
        }
        
        headers = {
            "x-api-key": self.api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json"
        }
        
        response = await self.client.post(
            ANTHROPIC_API_URL,
            json=payload,
            headers=headers
        )
        
        response.raise_for_status()
        data = response.json()
        
        # Extract content from response
        content = data.get("content", [])
        if not content:
            raise ValueError("Empty response from Claude API")
        
        text_content = content[0].get("text", "")
        
        # Extract JSON from response (Claude sometimes wraps in markdown)
        hooks_data = self._extract_json(text_content)
        
        hooks = []
        for i, hook_data in enumerate(hooks_data.get("hooks", [])):
            hooks.append(GeneratedHook(
                hook_text=hook_data["hook_text"],
                archetype=hook_data.get("archetype", "pattern_break"),
                confidence=float(hook_data.get("confidence", 0.8)),
                rationale=hook_data.get("rationale", ""),
                estimated_retention=float(hook_data.get("estimated_retention", 0.5)),
                variant_index=i
            ))
        
        logger.info(f"[ClaudeHook] Generated {len(hooks)} hooks via Claude API")
        return hooks
    
    def _extract_json(self, text: str) -> Dict[str, Any]:
        """Extract JSON from Claude's response (handles markdown wrapping)."""
        # Try to find JSON block
        if "```json" in text:
            start = text.find("```json") + 7
            end = text.find("```", start)
            json_str = text[start:end].strip()
        elif "```" in text:
            start = text.find("```") + 3
            end = text.find("```", start)
            json_str = text[start:end].strip()
        else:
            # Assume the whole thing is JSON, find first { and last }
            start = text.find("{")
            end = text.rfind("}") + 1
            json_str = text[start:end]
        
        return json.loads(json_str)
    
    def _fallback_generation(
        self,
        transcript: str,
        num_variants: int
    ) -> List[GeneratedHook]:
        """Fallback pattern-based generation when Claude is unavailable."""
        logger.info("[ClaudeHook] Using fallback pattern-based generation")
        
        # Extract first sentence
        first_sentence = transcript.split(".")[0] if transcript else "this"
        
        fallbacks = [
            GeneratedHook(
                hook_text=f"I stopped doing {first_sentence[:30]}... and everything changed",
                archetype="pattern_break",
                confidence=0.7,
                rationale="Pattern interrupt that creates curiosity",
                estimated_retention=0.65,
                variant_index=0
            ),
            GeneratedHook(
                hook_text=f"What nobody tells you about {first_sentence[:40]}",
                archetype="question",
                confidence=0.6,
                rationale="Knowledge gap hook",
                estimated_retention=0.6,
                variant_index=1
            ),
            GeneratedHook(
                hook_text=f"3 things I wish I knew about {first_sentence[:40]} sooner",
                archetype="promise",
                confidence=0.65,
                rationale="Promise of specific value",
                estimated_retention=0.62,
                variant_index=2
            )
        ]
        
        return fallbacks[:num_variants]
    
    async def generate_caption_from_hook(
        self,
        hook: GeneratedHook,
        transcript: str,
        platform: str = "tiktok",
        max_length: int = 100
    ) -> Tuple[str, List[str]]:
        """
        Generate a full caption from a hook using Claude.
        
        Returns:
            (caption, hashtags)
        """
        if not self.api_key:
            # Fallback
            return self._fallback_caption(hook, transcript, platform, max_length)
        
        system_prompt = f"""You are a short-form video caption writer.

Write a caption that:
1. Starts with the provided hook
2. Adds 1-2 sentences of context
3. Ends with a subtle CTA (question or follow prompt)
4. Total under {max_length} characters
5. Platform: {platform}

Return ONLY JSON: {{"caption": "...", "hashtags": ["#tag1", "#tag2", "#tag3"]}}"""
        
        user_prompt = f"""Hook: {hook.hook_text}

Transcript: {transcript[:500]}

Generate caption + 3-5 relevant hashtags."""
        
        try:
            payload = {
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 500,
                "system": system_prompt,
                "messages": [{"role": "user", "content": user_prompt}],
                "temperature": 0.7
            }
            
            headers = {
                "x-api-key": self.api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json"
            }
            
            response = await self.client.post(ANTHROPIC_API_URL, json=payload, headers=headers)
            response.raise_for_status()
            data = response.json()
            
            text_content = data.get("content", [{}])[0].get("text", "")
            result = self._extract_json(text_content)
            
            caption = result.get("caption", hook.hook_text)
            hashtags = result.get("hashtags", ["#shorts", "#viral", "#trending"])
            
            return caption, hashtags
        except Exception as e:
            logger.error(f"[ClaudeHook] Caption generation failed: {e}")
            return self._fallback_caption(hook, transcript, platform, max_length)
    
    def _fallback_caption(
        self,
        hook: GeneratedHook,
        transcript: str,
        platform: str,
        max_length: int
    ) -> Tuple[str, List[str]]:
        """Fallback caption generation."""
        body = transcript[:80] if transcript else "Watch this!"
        caption = f"{hook.hook_text}\n\n{body}...\n\nThoughts? 👇"
        
        if len(caption) > max_length:
            caption = caption[:max_length-3] + "..."
        
        hashtags = ["#shorts", "#viral", "#trending", f"#{platform}growth"]
        return caption, hashtags
    
    async def close(self):
        """Close HTTP client."""
        await self.client.aclose()


# Singleton instance
claude_hook_service = ClaudeHookService()
