"""
LLM Router-powered hook and caption generation service.

Replaces direct Claude API calls with tiered multi-model routing via LLMRouter.
The same interface is preserved so all downstream consumers (swarm agents,
remix service, content agent, API endpoints) get automatic cost optimization.

Hook generation → PREMIUM tier (Claude Sonnet 4.6, GPT-5.4)
Caption generation → STANDARD tier (GPT-5.4 Mini, Claude Haiku 4.5)
Hashtag optimization → ECONOMY tier (GPT-4.1 Nano)
"""

import logging
import os
import json
from typing import Dict, Any, List, Optional, Tuple
from dataclasses import dataclass

logger = logging.getLogger(__name__)


def _get_router():
    """Lazy import to avoid circular dependencies at module level."""
    from app.services.llm_router import get_router
    return get_router()


@dataclass
class GeneratedHook:
    """A hook generated by the LLM."""
    hook_text: str
    archetype: str
    confidence: float
    rationale: str
    estimated_retention: float
    variant_index: int


class ClaudeHookService:
    """Generate viral hooks and captions using tiered LLM routing.

    The name 'ClaudeHookService' is preserved for backward compatibility.
    Internally, calls are routed through LLMRouter to the most cost-effective
    model for each specific task.
    """

    ARCHETYPES = [
        "question", "promise", "pattern_break", "reaction",
        "story", "statistic", "challenge", "authority"
    ]

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.environ.get("ANTHROPIC_API_KEY", "")
        self._last_model_used: str = ""
        self._last_cost_usd: float = 0.0

        if not self.api_key and not os.environ.get("OPENAI_API_KEY"):
            logger.warning("[HookService] No ANTHROPIC_API_KEY or OPENAI_API_KEY set — "
                           "hooks will use fallback generation")

    @property
    def last_model_used(self) -> str:
        return self._last_model_used

    @property
    def last_cost_usd(self) -> float:
        return self._last_cost_usd

    async def generate_hooks(
        self,
        transcript_text: str,
        user_top_archetypes: List[Dict[str, Any]],
        num_variants: int = 3,
        platform: str = "tiktok",
        niche: Optional[str] = None
    ) -> List[GeneratedHook]:
        """Generate viral hook variants via LLMRouter (PREMIUM tier).

        Returns:
            List of GeneratedHook objects with metadata.
        """
        if not transcript_text:
            logger.warning("[HookService] Empty transcript — using fallback")
            return self._fallback_generation(transcript_text, num_variants)

        router = _get_router()
        system_prompt = self._build_system_prompt(platform, niche)
        user_prompt = self._build_user_prompt(transcript_text, user_top_archetypes, num_variants)

        try:
            result = await router.call(
                task_type="hook_generate",
                prompt=user_prompt,
                system_prompt=system_prompt,
                temperature=0.8,
                max_tokens=2000,
            )
            self._last_model_used = result["model_used"]
            self._last_cost_usd = result["cost_usd"]
            logger.info(f"[HookService] Generated hooks via {result['model_used']} "
                        f"cost=${result['cost_usd']:.5f} tokens_in={result['tokens_in']}")

            hooks_data = self._extract_json(result["content"])
            hooks = []
            for i, hook_data in enumerate(hooks_data.get("hooks", [])):
                hooks.append(GeneratedHook(
                    hook_text=hook_data["hook_text"],
                    archetype=hook_data.get("archetype", "pattern_break"),
                    confidence=float(hook_data.get("confidence", 0.8)),
                    rationale=hook_data.get("rationale", ""),
                    estimated_retention=float(hook_data.get("estimated_retention", 0.5)),
                    variant_index=i
                ))
            return hooks

        except Exception as e:
            logger.error(f"[HookService] Hook generation failed: {e}")
            return self._fallback_generation(transcript_text, num_variants)

    async def generate_caption_from_hook(
        self,
        hook: GeneratedHook,
        transcript: str,
        platform: str = "tiktok",
        max_length: int = 100
    ) -> Tuple[str, List[str]]:
        """Generate caption + hashtags via LLMRouter (STANDARD + ECONOMY tiers)."""
        router = _get_router()

        # Caption generation → STANDARD tier
        caption_system = (
            f"You are a short-form video caption writer for {platform}.\n\n"
            f"Write a caption that:\n"
            f"1. Starts with the provided hook\n"
            f"2. Adds 1-2 sentences of context\n"
            f"3. Ends with a subtle CTA\n"
            f"4. Total under {max_length} characters\n\n"
            f"Return ONLY JSON: {{\"caption\": \"...\", \"hashtags\": [\"#tag1\", \"#tag2\"]}}"
        )
        caption_prompt = f"Hook: {hook.hook_text}\n\nTranscript: {transcript[:500]}\n\nGenerate caption + 3-5 hashtags."

        try:
            caption_result = await router.call(
                task_type="caption_generate",
                prompt=caption_prompt,
                system_prompt=caption_system,
                temperature=0.7,
                max_tokens=500,
            )
            caption_data = self._extract_json(caption_result["content"])
            caption = caption_data.get("caption", hook.hook_text)
            hashtags = caption_data.get("hashtags", ["#shorts", "#viral", "#trending"])

            # Hashtag optimization → ECONOMY tier (supplement)
            if len(hashtags) < 3:
                extra_tags = await self._optimize_hashtags(transcript, platform)
                hashtags.extend(extra_tags)
                hashtags = list(dict.fromkeys(hashtags))[:8]  # Deduplicate, max 8

            self._last_model_used = caption_result["model_used"]
            self._last_cost_usd = caption_result["cost_usd"]

            logger.info(f"[HookService] Caption via {caption_result['model_used']} "
                        f"cost=${caption_result['cost_usd']:.5f}")
            return caption, hashtags

        except Exception as e:
            logger.error(f"[HookService] Caption generation failed: {e}")
            return self._fallback_caption(hook, transcript, platform, max_length)

    async def _optimize_hashtags(self, transcript: str, platform: str) -> List[str]:
        """Supplement hashtags via ECONOMY tier model."""
        router = _get_router()
        try:
            result = await router.call(
                task_type="hashtag_optimize",
                prompt=f"Generate 5 trending hashtags for this {platform} video:\n{transcript[:300]}",
                system_prompt="Return ONLY a JSON array of hashtag strings: [\"#tag1\", \"#tag2\"]",
                temperature=0.5,
                max_tokens=100,
            )
            return self._extract_json(result["content"])
        except Exception:
            return ["#shorts", "#viral", "#trending"]

    # ------------------------------------------------------------------
    # Prompt builders
    # ------------------------------------------------------------------

    def _build_system_prompt(self, platform: str, niche: Optional[str]) -> str:
        platform_guidance = {
            "tiktok": "TikTok: 1-2 seconds to capture attention. Hooks must be punchy, visual, and create immediate curiosity. Under 8 words if possible. Strong emotion or surprise.",
            "instagram": "Instagram Reels: Slightly more polished than TikTok. Hooks can be 10-12 words. Aspirational or relatable works well. Trendy language.",
            "youtube": "YouTube Shorts: Slightly longer hooks okay (15-20 words). Educational or 'how-to' angles perform well. Clear value proposition."
        }
        niche_guidance = f"The content niche is: {niche}. " if niche else ""
        return f"""You are a viral video hook specialist with expertise in short-form content optimization.

Your job is to generate attention-grabbing opening lines (hooks) for video clips.

Platform guidance: {platform_guidance.get(platform, platform_guidance['tiktok'])}

{niche_guidance}

Rules:
1. Each hook must create immediate curiosity, emotion, or surprise
2. Hooks should feel native to the platform — not corporate or sales-y
3. Use pattern interrupts, open loops, or emotional triggers
4. Never use clickbait that doesn't deliver on the content
5. Each hook should be unique — different angles on the same content
6. Rate each hook's predicted 3-second retention (0.0-1.0)
7. Classify each hook into an archetype: question, promise, pattern_break, reaction, story, statistic, challenge, authority

Return ONLY valid JSON in this exact format:
{{
  "hooks": [
    {{
      "hook_text": "The actual hook text",
      "archetype": "pattern_break",
      "confidence": 0.92,
      "rationale": "Why this hook works",
      "estimated_retention": 0.78
    }}
  ]
}}"""

    def _build_user_prompt(self, transcript: str, top_archetypes: List[Dict[str, Any]], num_variants: int) -> str:
        truncated = transcript[:2000] if len(transcript) > 2000 else transcript
        archetype_context = ""
        if top_archetypes:
            archetype_context = "User's top-performing hook archetypes (use these preferentially):\n"
            for i, arch in enumerate(top_archetypes[:3]):
                name = arch.get("pattern_type", arch.get("archetype_name", "unknown"))
                delta = arch.get("retention_delta_pct", arch.get("delta", 0))
                archetype_context += f"{i+1}. {name} (+{delta:.0f}% retention)\n"

        return f"""Generate {num_variants} unique, viral-worthy hooks for this video content.

{archetype_context}

Video transcript/content:
---
{truncated}
---

Generate {num_variants} hooks that:
1. Would stop someone from scrolling
2. Match the user's proven archetypes when possible
3. Each use a different angle/emotion
4. Are optimized for the platform

Return as JSON."""

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _extract_json(self, text: str) -> Dict[str, Any]:
        """Extract JSON from LLM response (handles markdown wrapping)."""
        if "```json" in text:
            start = text.find("```json") + 7
            end = text.find("```", start)
            json_str = text[start:end].strip()
        elif "```" in text:
            start = text.find("```") + 3
            end = text.find("```", start)
            json_str = text[start:end].strip()
        else:
            start = text.find("{")
            end = text.rfind("}") + 1
            json_str = text[start:end]
        return json.loads(json_str)

    def _fallback_generation(self, transcript: str, num_variants: int) -> List[GeneratedHook]:
        first_sentence = transcript.split(".")[0] if transcript else "this"
        fallbacks = [
            GeneratedHook(
                hook_text=f"I stopped doing {first_sentence[:30]}... and everything changed",
                archetype="pattern_break", confidence=0.7,
                rationale="Pattern interrupt that creates curiosity",
                estimated_retention=0.65, variant_index=0
            ),
            GeneratedHook(
                hook_text=f"What nobody tells you about {first_sentence[:40]}",
                archetype="question", confidence=0.6,
                rationale="Knowledge gap hook",
                estimated_retention=0.6, variant_index=1
            ),
            GeneratedHook(
                hook_text=f"3 things I wish I knew about {first_sentence[:40]} sooner",
                archetype="promise", confidence=0.65,
                rationale="Promise of specific value",
                estimated_retention=0.62, variant_index=2
            )
        ]
        return fallbacks[:num_variants]

    def _fallback_caption(self, hook: GeneratedHook, transcript: str, platform: str, max_length: int) -> Tuple[str, List[str]]:
        body = transcript[:80] if transcript else "Watch this!"
        caption = f"{hook.hook_text}\n\n{body}...\n\nThoughts? 👇"
        if len(caption) > max_length:
            caption = caption[:max_length-3] + "..."
        hashtags = ["#shorts", "#viral", "#trending", f"#{platform}growth"]
        return caption, hashtags


# Backward-compatible singleton
claude_hook_service = ClaudeHookService()
