"""
Music Library Service for clip remixing.

Loads tracks from music/catalog.json (generated by scripts/download_music_library.py).
Falls back to a small set of hard-coded tracks if the catalog is missing.

Sources (via catalog):
- Incompetech (Kevin MacLeod) — CC-BY 4.0, via archive.org
- Internet Archive netlabels — CC-licensed releases
- Run scripts/download_music_library.py to populate the catalog.
"""

import logging
import os
from typing import Dict, Any, List, Optional, Tuple
from dataclasses import dataclass
from pathlib import Path
import json

logger = logging.getLogger(__name__)


@dataclass
class MusicTrack:
    """A background music track."""
    id: str
    title: str
    artist: str
    mood: str  # high_energy, emotional, calm, dramatic, upbeat
    tempo_bpm: int
    duration_seconds: float
    file_path: Optional[str]  # Local path or None for external
    source: str  # "bundled", "tiktok", "epidemic", etc.
    license_type: str  # "royalty_free", "tiktok_commercial", "premium"
    volume_duck_factor: float = 0.15  # How much to reduce during speech


class MusicLibraryService:
    """
    Music library with mood-based track selection.

    Loads from music/catalog.json (199+ CC-licensed tracks from Incompetech
    and Internet Archive netlabels). Falls back to a minimal hard-coded set
    if no catalog exists.

    Populate the catalog:
        python3 backend/scripts/download_music_library.py
    """

    CATALOG_PATHS = [
        "/app/music/catalog.json",
        str(Path(__file__).parent.parent.parent / "app" / "music" / "catalog.json"),
    ]

    # Mood mapping from segment characteristics to music mood
    MOOD_MAPPING = {
        "high_energy": ["high_energy", "upbeat"],
        "emotional": ["emotional", "calm"],
        "calm": ["calm", "upbeat"],
        "dramatic": ["dramatic", "high_energy"],
        "neutral": ["upbeat", "calm"],
    }

    def __init__(self, music_dir: Optional[str] = None):
        self.music_dir = music_dir or "/app/music"
        self.tracks: List[MusicTrack] = []
        self._load_catalog()
        self._load_tiktok_tracks()

    def _load_catalog(self):
        """Load tracks from catalog.json; fall back to empty if missing."""
        catalog_path = None
        env_dir = os.environ.get("MUSIC_DIR", self.music_dir)
        candidate_paths = [
            os.path.join(env_dir, "catalog.json"),
            *self.CATALOG_PATHS,
        ]
        for p in candidate_paths:
            if os.path.exists(p):
                catalog_path = p
                break

        if not catalog_path:
            logger.warning("[MusicLib] catalog.json not found — run scripts/download_music_library.py")
            return

        try:
            with open(catalog_path) as f:
                catalog = json.load(f)
        except Exception as e:
            logger.error(f"[MusicLib] Failed to load catalog: {e}")
            return

        loaded = 0
        skipped = 0
        for entry in catalog.get("tracks", []):
            fp = entry.get("file_path", "")
            # Resolve relative paths against music directory
            if fp and not os.path.isabs(fp):
                fp = os.path.join(self.music_dir, fp)
            if fp and os.path.exists(fp):
                self.tracks.append(MusicTrack(
                    id=entry["id"],
                    title=entry["title"],
                    artist=entry["artist"],
                    mood=entry["mood"],
                    tempo_bpm=entry.get("tempo_bpm", 110),
                    duration_seconds=entry.get("duration_seconds", 120.0),
                    file_path=fp,
                    source=entry.get("source", "catalog"),
                    license_type=entry.get("license_type", "CC-BY"),
                    volume_duck_factor=entry.get("volume_duck_factor", 0.15),
                ))
                loaded += 1
            else:
                skipped += 1

        logger.info(f"[MusicLib] Loaded {loaded} tracks from catalog ({skipped} skipped — files missing)")

        if not self.tracks:
            logger.warning("[MusicLib] No tracks loaded — music mixing will be disabled")

    def _load_tiktok_tracks(self):
        """Load TikTok Commercial Music Library tracks if available."""
        tiktok_token = os.environ.get("TIKTOK_MUSIC_TOKEN")
        if not tiktok_token:
            return
        # TikTok Commercial Music Library integration placeholder
        logger.info("[MusicLib] TikTok music integration ready (token present)")
    
    def select_track(
        self,
        segment_energy: float,
        segment_salience: float,
        target_duration: float,
        exclude_tracks: Optional[List[str]] = None
    ) -> Optional[MusicTrack]:
        """
        Select the best music track for a segment.
        
        Args:
            segment_energy: 0.0-1.0 energy score
            segment_salience: 0.0-1.0 content importance
            target_duration: How long the clip will be
            exclude_tracks: Track IDs to exclude (for diversity across variants)
        
        Returns:
            Best matching MusicTrack or None
        """
        if not self.tracks:
            return None
        
        # Determine mood from energy/salience
        if segment_energy > 0.7 and segment_salience > 0.6:
            target_mood = "high_energy"
        elif segment_salience > 0.7:
            target_mood = "emotional"
        elif segment_energy < 0.3:
            target_mood = "calm"
        else:
            target_mood = "upbeat"
        
        # Get acceptable moods
        acceptable_moods = self.MOOD_MAPPING.get(target_mood, ["upbeat"])
        
        # Filter candidates
        exclude = set(exclude_tracks or [])
        candidates = [
            t for t in self.tracks
            if t.mood in acceptable_moods and t.id not in exclude
        ]
        
        if not candidates:
            # Fallback: any track not excluded
            candidates = [t for t in self.tracks if t.id not in exclude]
        
        if not candidates:
            # Final fallback: any track
            candidates = self.tracks
        
        # Score candidates by duration match and mood accuracy
        best_track = None
        best_score = -1.0
        
        for track in candidates:
            # Duration score: prefer tracks longer than needed but not too long
            duration_score = 1.0
            if track.duration_seconds < target_duration:
                duration_score = 0.3  # Too short — will loop awkwardly
            elif track.duration_seconds > target_duration * 3:
                duration_score = 0.7  # Too long — waste of storage
            
            # Mood accuracy score
            mood_score = 1.0 if track.mood == target_mood else 0.6
            
            # Energy match (tempo correlation)
            energy_tempo_map = {"high_energy": 120, "upbeat": 110, "dramatic": 100, "emotional": 75, "calm": 80}
            target_tempo = energy_tempo_map.get(target_mood, 100)
            tempo_diff = abs(track.tempo_bpm - target_tempo)
            tempo_score = max(0, 1.0 - (tempo_diff / 60.0))
            
            # Composite score
            score = (mood_score * 0.4) + (duration_score * 0.3) + (tempo_score * 0.3)
            
            if score > best_score:
                best_score = score
                best_track = track
        
        if best_track:
            logger.info(f"[MusicLib] Selected track '{best_track.title}' (mood={best_track.mood}, score={best_score:.2f})")
        
        return best_track
    
    def get_ffmpeg_mix_command(
        self,
        video_path: str,
        track: MusicTrack,
        output_path: str,
        video_duration: float,
        duck_during_speech: bool = True
    ) -> List[str]:
        """
        Build FFmpeg command to mix music with video.
        
        Implements:
        - Volume ducking during speech (sidechain compression simulation)
        - Loop music if shorter than video
        - Fade in/out
        - Music ends before video (don't cover the outro)
        """
        if not track.file_path or not os.path.exists(track.file_path):
            logger.warning(f"[MusicLib] Track file not found: {track.file_path}")
            return []
        
        # Music should end ~2 seconds before video for clean outro
        music_duration = min(video_duration - 2.0, track.duration_seconds)
        music_duration = max(music_duration, 3.0)  # At least 3 seconds
        
        # Build complex FFmpeg filter for music mixing
        # This creates a sidechain-like effect where music dips during speech
        filter_complex = (
            f"[1:a]aloop=loop=-1:size=2e+09,atrim=0:{music_duration},"
            f"afade=t=in:ss=0:d=1.0,afade=t=out:st={music_duration-1.5}:d=1.5,"
            f"volume={track.volume_duck_factor}[music];"
            f"[0:a][music]amix=inputs=2:duration=first:dropout_transition=2[aout]"
        )
        
        cmd = [
            "ffmpeg",
            "-y",
            "-i", video_path,
            "-i", track.file_path,
            "-filter_complex", filter_complex,
            "-map", "0:v",  # Keep original video
            "-map", "[aout]",  # Use mixed audio
            "-c:v", "copy",  # Don't re-encode video
            "-c:a", "aac",
            "-b:a", "192k",
            "-shortest",
            output_path
        ]
        
        return cmd
    
    def get_track_info(self, track_id: str) -> Optional[Dict[str, Any]]:
        """Get info about a specific track."""
        for track in self.tracks:
            if track.id == track_id:
                return {
                    "id": track.id,
                    "title": track.title,
                    "artist": track.artist,
                    "mood": track.mood,
                    "tempo_bpm": track.tempo_bpm,
                    "duration_seconds": track.duration_seconds,
                    "source": track.source,
                    "license_type": track.license_type
                }
        return None
    
    def list_tracks(self, mood: Optional[str] = None) -> List[Dict[str, Any]]:
        """List available tracks, optionally filtered by mood."""
        tracks = self.tracks
        if mood:
            tracks = [t for t in tracks if t.mood == mood]
        
        return [
            {
                "id": t.id,
                "title": t.title,
                "artist": t.artist,
                "mood": t.mood,
                "tempo_bpm": t.tempo_bpm,
                "duration_seconds": t.duration_seconds,
                "source": t.source,
                "license_type": t.license_type,
                "available": t.file_path is not None and os.path.exists(t.file_path)
            }
            for t in tracks
        ]
    
    def catalog_stats(self) -> Dict[str, Any]:
        """Return summary stats about the loaded catalog."""
        by_mood: Dict[str, int] = {}
        by_source: Dict[str, int] = {}
        for t in self.tracks:
            by_mood[t.mood] = by_mood.get(t.mood, 0) + 1
            by_source[t.source] = by_source.get(t.source, 0) + 1
        return {
            "total_tracks": len(self.tracks),
            "by_mood": by_mood,
            "by_source": by_source,
        }


# Singleton
music_library = MusicLibraryService()
music_library_service = music_library  # Backward compatibility alias
