"""
Dynamic Music Library Service with multi-source support and user uploads.

Loads tracks from:
- catalog.json (generated by scripts/download_music_library.py + rebalance_moods.py)
- User uploads (stored in /app/music/user_uploads/)

Features:
- Genre and vibe filtering
- Search
- User-uploaded track support

DEMO TRACK WARNING:
- Set DEMO_MODE=true env var to include demo tracks for testing
- REMOVE demo tracks before production deployment
- Run download_music_library.py to get real CC-BY 4.0 tracks
"""

import logging
import json
import os
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, asdict
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class MusicTrack:
    """A background music track."""
    id: str
    title: str
    artist: str
    genre: str
    vibe: str
    mood: str
    tempo_bpm: int
    duration_seconds: float
    file_path: Optional[str]
    source: str  # "internet_archive", "user_upload", "demo", etc.
    license_type: str
    volume_duck_factor: float = 0.15
    user_id: Optional[str] = None  # For user uploads
    uploaded_at: Optional[str] = None
    is_user_upload: bool = False


class MusicLibraryService:
    """
    Dynamic music library supporting catalog.json + user-uploaded tracks.
    
    IMPORTANT - DEMO TRACK REMOVAL:
    Before production/App Store deployment:
    1. Run: python scripts/download_music_library.py --max 200
    2. Run: python scripts/rebalance_moods.py
    3. Ensure /app/music/ contains real MP3s (not demo_*.mp3)
    4. Do NOT set DEMO_MODE=true in production
    
    Track sources:
    - catalog.json: auto-generated from /app/music/ downloads
    - user_uploads/: user-provided MP3 files
    """
    
    def __init__(self, music_dir: Optional[str] = None):
        self.music_dir = music_dir or "/app/music"
        self.tracks: List[MusicTrack] = []
        self._load_all()
    
    def _load_all(self):
        """Load all track sources."""
        self._load_catalog()
        self._load_user_uploads()
        logger.info(f"[MusicLib] Total tracks loaded: {len(self.tracks)}")
        
        # DEMO_MODE: set env DEMO_MODE=true to keep demo tracks for testing
        # IMPORTANT: Remove all demo tracks before production/App Store release
        if not os.environ.get("DEMO_MODE", "").lower() in ("true", "1", "yes"):
            self.tracks = [t for t in self.tracks if t.source != "demo"]
            logger.info(f"[MusicLib] Demo tracks excluded (set DEMO_MODE=true to include)")
        
        if not self.tracks:
            logger.warning("[MusicLib] No tracks available. Run scripts/download_music_library.py to populate.")
    
    def reload(self):
        """Reload all tracks (call after downloads or uploads)."""
        self.tracks.clear()
        self._load_all()
    
    def _load_catalog(self):
        """Load tracks from catalog.json."""
        catalog_path = Path(self.music_dir) / "catalog.json"
        
        if not catalog_path.exists():
            logger.info("[MusicLib] No catalog.json found — run scripts/download_music_library.py to populate")
            return
        
        try:
            with open(catalog_path) as f:
                catalog = json.load(f)
            
            for meta in catalog.get("tracks", []):
                track = MusicTrack(
                    id=meta.get("id", "unknown"),
                    title=meta.get("title", "Unknown"),
                    artist=meta.get("artist", "Unknown"),
                    genre=meta.get("genre", "misc"),
                    vibe=meta.get("vibe", "neutral"),
                    mood=meta.get("mood", self._vibe_to_mood(meta.get("vibe", "neutral"))),
                    tempo_bpm=meta.get("tempo_bpm", 100),
                    duration_seconds=meta.get("duration_seconds", 120),
                    file_path=meta.get("file_path"),
                    source=meta.get("source", "unknown"),
                    license_type=meta.get("license_type", meta.get("license", "unknown")),
                )
                
                if track.file_path and os.path.exists(track.file_path):
                    self.tracks.append(track)
                    logger.info(f"[MusicLib] Loaded: {track.title} ({track.source})")
                else:
                    logger.warning(f"[MusicLib] Missing file: {track.file_path}")
            
            logger.info(f"[MusicLib] Loaded {len(self.tracks)} tracks from catalog.json")
            
        except Exception as e:
            logger.error(f"[MusicLib] Failed to load catalog: {e}")
    
    def _load_user_uploads(self):
        """Load user-uploaded tracks from user_uploads/ subdirectory."""
        user_dir = Path(self.music_dir) / "user_uploads"
        if not user_dir.exists():
            return
        
        for meta_file in user_dir.glob("*.json"):
            try:
                with open(meta_file) as f:
                    meta = json.load(f)
                
                mp3_file = meta_file.with_suffix(".mp3")
                if not mp3_file.exists():
                    continue
                
                track = MusicTrack(
                    id=f"user_{meta.get('user_id', 'unknown')}_{meta_file.stem}",
                    title=meta.get("title", "Untitled"),
                    artist=meta.get("artist", "Unknown"),
                    genre=meta.get("genre", "misc"),
                    vibe=meta.get("vibe", "neutral"),
                    mood=meta.get("mood", self._vibe_to_mood(meta.get("vibe", "neutral"))),
                    tempo_bpm=meta.get("tempo_bpm", 100),
                    duration_seconds=meta.get("duration_seconds", 120),
                    file_path=str(mp3_file),
                    source="user_upload",
                    license_type=meta.get("license", "user_owned"),
                    user_id=meta.get("user_id"),
                    uploaded_at=meta.get("uploaded_at"),
                    is_user_upload=True,
                )
                
                self.tracks.append(track)
                logger.info(f"[MusicLib] Loaded user upload: {track.title}")
                
            except Exception as e:
                logger.error(f"[MusicLib] Failed to load user upload {meta_file}: {e}")
    
    def _vibe_to_mood(self, vibe: str) -> str:
        """Map vibe to mood category."""
        mapping = {
            "energetic": "high_energy", "powerful": "high_energy", "rebellious": "high_energy",
            "happy": "upbeat", "catchy": "upbeat", "bright": "upbeat",
            "calm": "calm", "peaceful": "calm", "relaxed": "calm", "dreamy": "calm",
            "emotional": "emotional", "elegant": "emotional", "nostalgic": "emotional",
            "dramatic": "dramatic", "epic": "dramatic",
            "smooth": "calm", "sophisticated": "calm",
            "focused": "high_energy", "chill": "calm",
            "urban": "high_energy", "confident": "high_energy",
            "warm": "upbeat", "authentic": "upbeat",
            "exotic": "dramatic", "cultural": "dramatic", "vibrant": "upbeat",
            "neutral": "calm",
        }
        return mapping.get(vibe.lower(), "calm")
    
    def add_user_upload(self, file_path: str, user_id: str, title: str, 
                        artist: str = "Unknown", genre: str = "misc", 
                        vibe: str = "neutral", license_type: str = "user_owned") -> MusicTrack:
        """Add a user-uploaded track to the library."""
        user_dir = Path(self.music_dir) / "user_uploads"
        user_dir.mkdir(parents=True, exist_ok=True)
        
        # Move file to user_uploads directory
        dest = user_dir / f"{Path(file_path).stem}.mp3"
        os.rename(file_path, str(dest))
        
        # Detect duration
        duration = 120.0
        try:
            from mutagen.mp3 import MP3
            audio = MP3(str(dest))
            duration = float(audio.info.length)
        except:
            pass
        
        track = MusicTrack(
            id=f"user_{user_id}_{dest.stem}",
            title=title,
            artist=artist,
            genre=genre,
            vibe=vibe,
            mood=self._vibe_to_mood(vibe),
            tempo_bpm=100,
            duration_seconds=duration,
            file_path=str(dest),
            source="user_upload",
            license_type=license_type,
            user_id=user_id,
            uploaded_at=str(__import__('datetime').datetime.utcnow().isoformat()),
            is_user_upload=True,
        )
        
        # Save metadata
        meta = {
            "title": title,
            "artist": artist,
            "genre": genre,
            "vibe": vibe,
            "duration_seconds": duration,
            "user_id": user_id,
            "uploaded_at": track.uploaded_at,
            "license": license_type,
        }
        with open(dest.with_suffix(".json"), "w") as f:
            json.dump(meta, f, indent=2)
        
        self.tracks.append(track)
        logger.info(f"[MusicLib] Added user upload: {title}")
        return track
    
    def list_tracks(
        self, 
        mood: Optional[str] = None,
        genre: Optional[str] = None,
        vibe: Optional[str] = None,
        source: Optional[str] = None,
        user_id: Optional[str] = None,
        search: Optional[str] = None,
    ) -> List[Dict[str, Any]]:
        """List tracks with multi-dimensional filtering."""
        tracks = self.tracks
        
        if mood:
            tracks = [t for t in tracks if t.mood == mood]
        if genre:
            tracks = [t for t in tracks if t.genre.lower() == genre.lower()]
        if vibe:
            tracks = [t for t in tracks if t.vibe.lower() == vibe.lower()]
        if source:
            tracks = [t for t in tracks if t.source == source]
        if user_id:
            tracks = [t for t in tracks if t.user_id == user_id]
        if search:
            search_lower = search.lower()
            tracks = [
                t for t in tracks 
                if search_lower in t.title.lower() 
                or search_lower in t.artist.lower()
                or search_lower in t.genre.lower()
                or search_lower in t.vibe.lower()
            ]
        
        return [self._track_to_dict(t) for t in tracks]
    
    def get_track_info(self, track_id: str) -> Optional[Dict[str, Any]]:
        """Get info about a specific track."""
        for track in self.tracks:
            if track.id == track_id:
                return self._track_to_dict(track)
        return None
    
    def get_distinct_values(self) -> Dict[str, List[str]]:
        """Get all distinct genres, vibes, moods, and sources for filters."""
        return {
            "genres": sorted(set(t.genre for t in self.tracks)),
            "vibes": sorted(set(t.vibe for t in self.tracks)),
            "moods": sorted(set(t.mood for t in self.tracks)),
            "sources": sorted(set(t.source for t in self.tracks)),
        }
    
    def _track_to_dict(self, track: MusicTrack) -> Dict[str, Any]:
        """Convert track to API response dict."""
        return {
            "id": track.id,
            "title": track.title,
            "artist": track.artist,
            "genre": track.genre,
            "vibe": track.vibe,
            "mood": track.mood,
            "tempo_bpm": track.tempo_bpm,
            "duration_seconds": track.duration_seconds,
            "source": track.source,
            "license_type": track.license_type,
            "available": track.file_path is not None and os.path.exists(track.file_path),
            "is_user_upload": track.is_user_upload,
            "user_id": track.user_id,
        }
    
    def get_ffmpeg_mix_command(
        self,
        video_path: str,
        track_id: str,
        output_path: str,
        video_duration: float,
        duck_during_speech: bool = True
    ) -> List[str]:
        """Build FFmpeg command to mix music with video."""
        track = None
        for t in self.tracks:
            if t.id == track_id:
                track = t
                break
        
        if not track or not track.file_path or not os.path.exists(track.file_path):
            logger.warning(f"[MusicLib] Track not found: {track_id}")
            return []
        
        music_duration = min(video_duration - 2.0, track.duration_seconds)
        music_duration = max(music_duration, 3.0)
        
        filter_complex = (
            f"[1:a]aloop=loop=-1:size=2e+09,atrim=0:{music_duration},"
            f"afade=t=in:ss=0:d=1.0,afade=t=out:st={music_duration-1.5}:d=1.5,"
            f"volume={track.volume_duck_factor}[music];"
            f"[0:a][music]amix=inputs=2:duration=first:dropout_transition=2[aout]"
        )
        
        return [
            "ffmpeg", "-y",
            "-i", video_path,
            "-i", track.file_path,
            "-filter_complex", filter_complex,
            "-map", "0:v",
            "-map", "[aout]",
            "-c:v", "copy",
            "-c:a", "aac", "-b:a", "192k",
            "-shortest",
            output_path
        ]
    
    def select_track(
        self,
        segment_energy: float,
        segment_salience: float,
        target_duration: float,
        exclude_tracks: Optional[List[str]] = None
    ) -> Optional[MusicTrack]:
        """Select best track for a segment."""
        if not self.tracks:
            return None
        
        if segment_energy > 0.7 and segment_salience > 0.6:
            target_mood = "high_energy"
        elif segment_salience > 0.7:
            target_mood = "emotional"
        elif segment_energy < 0.3:
            target_mood = "calm"
        else:
            target_mood = "upbeat"
        
        exclude = set(exclude_tracks or [])
        candidates = [t for t in self.tracks if t.id not in exclude]
        
        if not candidates:
            candidates = self.tracks
        
        best_track = None
        best_score = -1.0
        
        for track in candidates:
            duration_score = 1.0
            if track.duration_seconds < target_duration:
                duration_score = 0.3
            elif track.duration_seconds > target_duration * 3:
                duration_score = 0.7
            
            mood_score = 1.0 if track.mood == target_mood else 0.6
            
            energy_tempo_map = {
                "high_energy": 120, "upbeat": 110, "dramatic": 100,
                "emotional": 75, "calm": 80
            }
            target_tempo = energy_tempo_map.get(target_mood, 100)
            tempo_diff = abs(track.tempo_bpm - target_tempo)
            tempo_score = max(0, 1.0 - (tempo_diff / 60.0))
            
            score = (mood_score * 0.4) + (duration_score * 0.3) + (tempo_score * 0.3)
            
            if score > best_score:
                best_score = score
                best_track = track
        
        return best_track


# Singleton
music_library_service = MusicLibraryService()
